### ISSUE TITLE
Rails 3.2.9 Jruby 1.7.0 Jruby-Rack 1.1.12  cache error: instance of IO needed

### ISSUE THREAD

**Issue by twiz718** [jruby/jruby-rack#136]
Every asset request is reporting this INFO message in the logs in production:

2012-12-12 16:05:32 -0600 INFO: Served asset /jquery.ui.base.css - 304 Not Modified (0ms)
2012-12-12 16:05:32 -0600 INFO: cache error: instance of IO needed
org/jruby/RubyMarshal.java:145:in `load'
/srv/www/workhub/shared/bundle/jruby/1.9/gems/actionpack-3.2.9/lib/action_dispatch/http/rack_cache.rb:18:in `read'
/srv/www/workhub/shared/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/metastore.rb:30:in `lookup'
/srv/www/workhub/shared/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:169:in `lookup'
/srv/www/workhub/shared/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
/srv/www/workhub/shared/bundle/jruby/1.9/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
/srv/www/workhub/shared/bundle/jruby/1.9/gems/railties-3.2.9/lib/rails/engine.rb:479:in `call'
/srv/www/workhub/shared/bundle/jruby/1.9/gems/railties-3.2.9/lib/rails/application.rb:223:in `call'
file:/home/capistrano/.rvm/gems/jruby-1.7.0@workhub/gems/jruby-rack-1.1.12/lib/jruby-rack-1.1.12.jar!/rack/handler/servlet.rb:22:in `call'

**Comment by kares** [comment]
closing as invalid as this wasn't jruby-rack specific but rather a jruby issue.
