### ISSUE TITLE
Need release to address rack update, XSS fix

### ISSUE THREAD

**Issue by headius** [jruby/jruby-rack#190]
See jruby/jruby-rack#189 for a PR merged to update to a newer rack, which fixes an XSS issue in ShowError. jruby-rack enables ShowError by default, so we should get an updated release out for this ASAP.

**Comment by kares** [comment]
1.1.18 is out with a fix ... same [comment](https://github.com/jruby/jruby-rack/pull/189#issuecomment-69882609) applies here as on #189
