### ISSUE TITLE
Response to preflight request is intercepted by servlet

### ISSUE THREAD

**Issue by joe-re** [jruby/jruby-rack#193]
This issue's cause is same as #153 .

I think that we have to deal with not only 'Allow' header but also 'Access-Control-Allow-Origin' header.

**Comment by kares** [comment]
@joe-re we would need exact information (preferably with source links) if you traced this down already ...

**Comment by joe-re** [comment]
@kares 
I'm sorry, I misunderstood...

The commad and response below was result that I tried.
```
$ curl -i -X OPTIONS 'http://localhost/api/v1/infomation'
HTTP/1.1 200 OK
Date: Thu, 29 Jan 2015 01:49:39 GMT
Allow: GET, HEAD, POST, PUT, DELETE, OPTIONS
Content-Length: 0
Connection: close
```

But I implements OPTIONS method. And I misread 592c17f...

So I thought to due to not enough dealt with CORS.

But I couldn't reproduce it now.

Probably this is my miss.

Old library had get mixed in war when I use warble,etc...
