### ISSUE TITLE
Release a new version containing Rack >= 1.5.4

### ISSUE THREAD

**Issue by TheSavior** [jruby/jruby-rack#196]
There was a security issue posted with Rack that is fixed in versions >= 1.5.4 and 1.6.2.

https://groups.google.com/forum/#!topic/rubyonrails-security/gcUbICUmKMc

The gemfile.lock for this project specifies 1.6.0. Could we get a new version of jruby-rack that bumps the version?

**Comment by kares** [comment]
the **1.1.19** release bundles rack **1.5.5**
