### ISSUE TITLE
jruby.rack.logging Parameter not working

### ISSUE THREAD

**Issue by dimitertodorov** [jruby/jruby-rack#204]
Hi,

Trying to get my Rails app to log to a custom file on Tomcat 8.
I have tried setting the logging parameter to log4j or slf4j, but the output keeps showing up in my catalina.out.

config.webxml.jruby.rack.logging = "log4j"
OR
config.webxml.jruby.rack.logging = "slf4j"

What is the easiest way to redirect the Rails.logger output to a custom file on Tomcat 8.

D

**Comment by kares** [comment]
only puts output would show up on catalina.out. as for the rest there's little details here - you pbly did not configure the logging backend. the easiest way might have been setting up a custom Rails logger the usual way.
