### ISSUE TITLE
exception in websphere

### ISSUE THREAD

**Issue by lupitagares** [jruby/jruby-rack#208]
Hi i am trying to fix an incident in my job, the log shows this exception:

com.ibm.ws.webcontainer.filter.filterinstancewrapper service SRVE8109W: Uncaught exception thrown by filter action2: java.io.FileNotFoundException: xxxx SRVE0190E: File not found

and i don't know what is that thing?, where it comes from?, nothing! can you help me? plssss i'm going crazy!

the app is made in java, struts and jsp, jquery.
thanks a lot!

**Comment by kares** [comment]
please understand what this tracker is for, from the app details it's no where clear that you're using jruby-rack. `FNFE` is a generic exception, I recommend looking at the stack-trace part coming from your app - do not get confused by the similarity reported here (if you're not running any JRuby).
