### ISSUE TITLE
Requests are handled before rails app is fully loaded

### ISSUE THREAD

**Issue by jlahtinen** [jruby/jruby-rack#217]
Not sure if this is true or not.

Is it possible that some of early requests fails to uninitialized constant errors when rails is not fully loaded or is this a rails configuration problem?

Can jruby-rack detect when rails is fully loaded?

**Comment by kares** [comment]
should not been the case, if you're seeing such behavior we would need details (ideally a reproducer on a simple Rails app).

**Comment by jlahtinen** [comment]
Thanks for the reply. I will keep searching if this issue raises again.
