### ISSUE TITLE
Multiline environment variables set with jruby.runtime.env

### ISSUE THREAD

**Issue by 7h3kk1d** [jruby/jruby-rack#232]
As far as I can tell there's no way to set `jruby.runtime.env` with values that are multiline env vars. This is useful if you're environment variables contain certificates. Is this something that would be open to a pull request or feature addition?

**Comment by kares** [comment]
Hey Alexander, probably if there's a need for this kind of features. Any reason why you would not set those from `ENV`?

**Comment by 7h3kk1d** [comment]
I managed to work around my use case by doing that. We had something that was linting ENV to make sure nothing was slipping by.
