### ISSUE TITLE
Deprecation warnings under JRuby 9.2.x

### ISSUE THREAD

**Issue by ryanfb** [jruby/jruby-rack#233]
For a Rails app running under Tomcat via Warbler, upgrading from JRuby 9.1.17.0 (Ruby 2.3.3 compatibility) to JRuby 9.2.14.0 (Ruby 2.5.7 compatibility) with jruby-rack 1.1.21 gives me the following new deprecation warnings on application startup:

```
uri:classloader:/jruby/rack/response.rb:294: warning: constant ::Fixnum is deprecated
uri:classloader:/jruby/rack/core_ext.rb:26: warning: constant ::NativeException is deprecated
```
These correspond to:
* https://github.com/jruby/jruby-rack/blob/1.1.21/src/main/ruby/jruby/rack/response.rb#L294
* https://github.com/jruby/jruby-rack/blob/1.1.21/src/main/ruby/jruby/rack/core_ext.rb#L26

Apparently, `Fixnum` has been replaced by `Integer`, and seems to already be fixed on `master` (via removal), just not in any jruby-rack release. I'm not sure on the best path forward for `NativeException`, or the best way to be compatible with both Ruby 2.3.3 and 2.5.7+ if that's desired.

**Comment by kares** [comment]
the issue is expected to be resolved, please upgrade to >= 1.1.22
